George Rodriguez, Augus Sanchez,

Dataset : https://www.kaggle.com/datasets/smritisingh1997/car-salescsv

In [ ]:
import numpy as nm
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
#import and upload data:
from google.colab import files
uploaded = files.upload()

Saving car_sales.csv to car_sales.csv

In [ ]:
df=pd.read_csv('car_sales.csv')
df

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4
...,...,...,...,...,...,...,...,...,...
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535
4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520
4343,Toyota,14200.0,sedan,31,NaN,Petrol,yes,2014,Corolla
4344,Volkswagen,13500.0,van,124,2.0,Diesel,yes,2013,T5 (Transporter)

In [ ]:
df = df.drop(columns=['Registration'])

In [ ]:
# eliminate the data where null value in Price and EngineV feature
df = df.dropna(subset=['Price','EngineV','Year'])
df

,Brand,Price,Body,Mileage,EngineV,Engine Type,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,2011,Rav 4
...,...,...,...,...,...,...,...,...
4339,Toyota,17900.0,sedan,35,1.6,Petrol,2014,Corolla
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,1999,535
4342,BMW,8000.0,sedan,194,2.0,Petrol,1985,520
4344,Volkswagen,13500.0,van,124,2.0,Diesel,2013,T5 (Transporter)

In [ ]:
df['Brand'] = le.fit_transform(df['Brand'])
df['Body'] = le.fit_transform(df['Body'])
df['Engine Type'] = le.fit_transform(df['Engine Type'])
df['Model'] = le.fit_transform(df['Model'])
df

/tmp/ipykernel_810/2616431386.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Brand'] = le.fit_transform(df['Brand'])
/tmp/ipykernel_810/2616431386.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Body'] = le.fit_transform(df['Body'])
/tmp/ipykernel_810/2616431386.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Engine Type'] = le.fit_transform(df['Engine Type'])
/tmp/ipykernel_810/2616431386.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Model'] = le.fit_transform(df['Model'])

      Brand     Price  Body  Mileage  EngineV  Engine Type  Year  Model
0         1    4200.0     3      277      2.0            3  1991     18
1         2    7900.0     5      427      2.9            0  1999    254
2         2   13300.0     3      358      5.0            1  2003    226
3         0   23000.0     0      240      4.2            3  2007    213
4         5   18300.0     0      120      2.0            3  2011    216
...     ...       ...   ...      ...      ...          ...   ...    ...
4339      5   17900.0     3       35      1.6            3  2014    108
4340      2  125000.0     3        9      3.0            0  2014    222
4341      1    6500.0     3        1      3.5            3  1999     37
4342      1    8000.0     3      194      2.0            3  1985     31
4344      6   13500.0     5      124      2.0            0  2013    271

[3878 rows x 8 columns]

In [ ]:
df = df[df['Mileage'] != 0]
df

      Brand     Price  Body  Mileage  EngineV  Engine Type  Year  Model
0         1    4200.0     3      277      2.0            3  1991     18
1         2    7900.0     5      427      2.9            0  1999    261
2         2   13300.0     3      358      5.0            1  2003    232
3         0   23000.0     0      240      4.2            3  2007    219
4         5   18300.0     0      120      2.0            3  2011    222
...     ...       ...   ...      ...      ...          ...   ...    ...
4339      5   17900.0     3       35      1.6            3  2014    110
4340      2  125000.0     3        9      3.0            0  2014    228
4341      1    6500.0     3        1      3.5            3  1999     37
4342      1    8000.0     3      194      2.0            3  1985     31
4344      6   13500.0     5      124      2.0            0  2013    278

[3878 rows x 8 columns]

In [ ]:
#df_scaled = preprocessing.scale(df)
#df_scaled = pd.DataFrame(df_scaled, columns=df.columns)

In [ ]:
x = df[['Model','Mileage','Year','EngineV','Brand','Body','Engine Type']]
y = df['Price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 263604851.28765807
R-squared: 0.3822368349837878

In [ ]:
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

def get_prediction():
    cols = ['Model','Mileage','Year','EngineV','Brand','Body','Engine Type']
    while True:
        try:
            model_code = int(input("Enter Model code: "))
            mileage = float(input("Enter Mileage: "))
            year = int(input("Enter Year: "))
            enginev = float(input("Enter EngineV: "))
            brand_code = int(input("Enter Brand code: "))
            body_code = int(input("Enter Body code: "))
            engine_type_code = int(input("Enter Engine Type code: "))

            input_df = pd.DataFrame(
                [[model_code, mileage, year, enginev, brand_code, body_code, engine_type_code]],
                columns=cols
            )

            predicted_price = lr_model.predict(input_df)[0]
            print(f"Predicted price: ${predicted_price:.2f}")
            break


        except ValueError:
            print("Invalid input. Please enter numeric values.")
        except Exception as e:
            print(f"An error occurred: {e}")
            break

while True:
    get_prediction()
    another = input("Do you want to predict another price? (yes/no): ")
    if another.lower() != "yes":
        break

Predicted price: $-48647.02

Summary

This program takes a spreadsheet of car listings and uses it to learn a basic pattern for how car price changes based on things like the car’s model, brand, year, mileage, engine size, body style, and engine type. It first cleans the data by removing incomplete or strange entries, then it converts words (like “Toyota” or “SUV”) into numeric codes so the computer can work with them. After that, it trains a simple pricing predictor and checks how accurate it is using standard scoring methods. Finally, it lets someone type in a car’s details and it will estimate the price based on what it learned from the dataset.